### ISSUE TITLE
version 0.25.302-43 - on every start pop up "unable to update" 

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#10]
Last muon version autoupdates to core but 0.25.302-43 portable us unable so it brings evvery time a remark of unable to update.
I would like not to autoupdate nor to have (if possible) the reminder...
Thanks

**Comment by cra3yk** [comment]
1+
Reverted back to .42

**Comment by crazy-max** [comment]
@caspertone2003 @cra3yk Should be ok with release 44 : https://portapps.github.io/app/brave-portable/#download

**Comment by caspertone2003** [comment]
@crazy-max 
Thanks, confirmed ok
