### ISSUE TITLE
over 3 months no update

### ISSUE THREAD

**Issue by annalenager** [portapps/brave-portable#105]
i so disappointed, over 3 months no update. it is now 1.37.116.
there were several chrome updates.
over 200 security fix
more than 8 brave versions

the project is a danger.
it is dead at 1.34.80

**Comment by Radu273** [comment]
im also wondering what is with the project?

**Comment by Troggg** [comment]
Was wondering also what was up with no new releases

**Comment by crazy-max** [comment]
Updated: https://portapps.io/app/brave-portable/#download

> the project is a danger.

> im also wondering what is with the project?

> Was wondering also what was up with no new releases

It's an open source project. Feel free to contribute.

**Comment by STSMHQ** [comment]
> Updated: https://portapps.io/app/brave-portable/#download
> 
> > the project is a danger.
> 
> > im also wondering what is with the project?
> 
> > Was wondering also what was up with no new releases
> 
> It's an open source project. Feel free to contribute.

@crazy-max Thanks :3
