### ISSUE TITLE
Portability question

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#11]
@crazy-max 

While we wait for the patch to brave-core, and that they deploy the sessions feature, I kept using 0.25.

I have a portability issue. It happens at least in 0.25.302-44 . 

I opened in a session tab a gmail session (log in) and closed the browser. Configured to NOT deleting anything and re-opening same taps as when closed.
Reopening the browser works perfect. Gmail session kept.

If I zip all the folder containing all of the portable browser, unzip open it in another computer, and open the browser, session information is lost. Perhaps it is gmail that detects the change? In any case this makes the experience not fully portable. Is there any solution? I understand that working in a dead release has no much interest... but I suspect that session control will take its time... and it is essential to have several open sessions in parallel.

On another record... it is possible to use two brave portables at the same time without interference one to the other?

Thanks in advance,
CT.

**Comment by crazy-max** [comment]
@caspertone2003

> I have a portability issue. It happens at least in 0.25.302-44 .

[0.61.5](https://github.com/brave/brave-browser/releases/tag/v0.61.5) is out so we will focus on this branch :)

> On another record... it is possible to use two brave portables at the same time without interference one to the other?

Never tried multi instance

**Comment by caspertone2003** [comment]
Tears Tears

**Comment by crazy-max** [comment]
@caspertone2003 Multi instance works for me on 0.61

**Comment by caspertone2003** [comment]
@crazy-max 
I can confirm that it works in 0.25 as well.
By the way, 0.61 goes smoothly. Let me hope sessions come back and come back soon...
I would like to fully move to 0.61 for the ability to use chrome plugins.
In the mean time I use 0.25 to access gmail accounts in different sessions and 0.61 for the rest of activities.
Yet to check that in 0.61 cookies are conserved from one pc to another 
CT

**Comment by caspertone2003** [comment]
@crazy-max 
I can confirm that 0.61 is portable within same machine, in terms of extensions, parameters of extensions, open tabs and bookmarks.
I installed OneTab (from Chrome extensions) and moved the folder around - no glitch at all.
Not tested yet in a different PC (aka USB portability).
CT
