### ISSUE TITLE
Directory not empty

### ISSUE THREAD

**Issue by m-i-h** [portapps/brave-portable#114]
Keep getting "directory not empty" error when trying to setup the portable version. I DO choose the option to install to the directory anyway, but it fails, regardless. I've also tried creating new folders in various places, and tried the last couple of versions. Same thing. This is for a new installation to a Windows 10 computer. I don't have a prior version installed, but when I tried that option just in case, it's missing the .json file (as it logically should).

![Installation_error_directory](https://user-images.githubusercontent.com/110124472/181341254-4e42fa21-c86e-44af-bdfb-5991fe266f94.jpg)
.

**Comment by Zaqm** [comment]
@crazy-max

**Comment by crazy-max** [comment]
Can't repro with latest version https://github.com/portapps/brave-portable/releases/download/1.40.113-82/brave-portable-win64-1.40.113-82-setup.exe.

![image](https://user-images.githubusercontent.com/1951866/184508657-048bb6cf-88f7-4f18-ad4c-e7361c6e2bb6.png)

![image](https://user-images.githubusercontent.com/1951866/184508661-14bd0ce7-71a7-4e3d-977d-d0ffe392bfb8.png)

![image](https://user-images.githubusercontent.com/1951866/184508665-b527d47b-cb85-468e-930f-3bc5d423b6f2.png)


Are you trying to install on network drive?
