### ISSUE TITLE
New / PorBraveUpd - Portable Brave Updater

### ISSUE THREAD

**Issue by Dev-Hobby** [portapps/brave-portable#117]
Hi @crazy-max 
.
.
See Project
PorBraveUpd - Portable Brave Updater By @UndertakerBen
https://github.com/UndertakerBen/PorBraveUpd
.
.
.
![0ed](https://user-images.githubusercontent.com/55116927/185754004-79ec536b-2675-402b-8276-884bb5830321.png)
.

**Comment by Zaqm** [comment]
@everyone
@raycekar  @RifHut @webgoto @pstein @m-i-h @vinayaketx @STSMHQ @annalenager @obstruction @zeref-dragneel @cisko99za @compusolve-rsa @teamayu @elyckir @JotaOdiceu @ferino75 @ghost @Aqua1ung @jamalso @AdKiller @Chaython @crabshank @DJMo13 @alexeiz @rampageX @WrongGuy @gifthubbro @st333v @beppe9000 @mastino21 @alepodj @ofernandofilo @angelog0 @VirtualW @5H00T4 @Ergonomicmike @d-faure @tomasz1986 @Salin1810 @luixxiul       
@caspertone2003 @justmwa @kolobok55 @git-nico

**Comment by Dev-Hobby** [comment]
??????? @crazy-max

**Comment by STSMHQ** [comment]
@Dev-Hobby Sorry for the delay. Thanks for pinging me. What's the main difference between that project and @crazy-max one?! What are you using and why?
