### ISSUE TITLE
v 1.43.89  --disable-machine-id not working in brave

### ISSUE THREAD

**Issue by AdamZielinski6** [portapps/brave-portable#122]
--disable-machine-id not working

Version v 1.43.89 of Brave portable does not disable my machine id anymore. In the previous versions it was a very neat functionality. Is there anything that can be done about this? I wish my machine id was hidden like it was before. 

Configuration
version 1.43.89
Operating system Windows 10 home 64 bits

Screenshot:
[screenshot](https://i.ibb.co/DMZDZkF/device-id-brave.jpg)

**Comment by crazy-max** [comment]
related to https://github.com/portapps/brave-portable/issues/33
