### ISSUE TITLE
brave browser updates fail

### ISSUE THREAD

**Issue by mutsuura** [portapps/brave-portable#124]
#### Steps to reproduce this issue

1.Settings -> About Brave
2.Displays "...error occurred while checking for updates"
3.

#### Expected behaviour

> Tell me what should happen

Should display current version and available update if any.

#### Actual behaviour

> Tell me what happens instead

Fails to validate any available updates.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 11

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by Chaython** [comment]
You can drop the updated executable from https://github.com/brave/brave-browser/releases to ..\Brave Portable\app

**Comment by espanafly** [comment]
see https://github.com/portapps/brave-portable/issues/134#issue-1640713578

**Comment by Chaython** [comment]
I finally got around to creating a script, run it from the brave portable dir https://github.com/Chaython/Brave-Portable-Updater
