### ISSUE TITLE
Time for an update please: latest version of Brave is v1.46.144

### ISSUE THREAD

**Issue by YesTrustMe** [portapps/brave-portable#129]
On December 14, 2022 released: https://brave.com/latest/

**Comment by Chaython** [comment]
You can drop the updated executable from https://github.com/brave/brave-browser/releases to ..\Brave Portable\app

**Comment by greatwolf** [comment]
Quick PSA, it's possible to update by hand. https://github.com/portapps/brave-portable/blob/master/build.properties contains this field `atf.win64.url = https://brave-browser-downloads.s3.brave.com/latest/brave_installer-x64.exe`. 

 - Download 'brave_installer-x64.exe' from that link.
 - Don't run the self-extracting executable. Instead open it with 7z. Open 'chrome.7z' that's inside.
 - Find 'Chrome-bin' folder inside and open it.
 - Now extract all the contents from there into your existing portable Brave location in the subfolder './app'.

The same files should be present if you picked the right location(eg. brave.exe, chrome_proxy.exe, version folder etc.). Have the extraction overwrite your existing files with the updated versions from 'brave_installer-x64.exe'.
