### ISSUE TITLE
Some suggestions for .61x installation/update

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#13]
Seems there will be a long update road until brave-core 1.0RC... Some increase of efficiency would be welcomed:

A) when launched, it selects a default directory for installation; would like that proposed installation in the directory where the .exe is located and that  /brave-portable is not appended authomatically.

B) Would like to launch a silent update, to update previous version located in the directory where install exe is located. .exe could detect that there is already a previous version installed in that directory and just question if update or not; after yes, no more questions...

C) I ususally delete locales that I do not use. Update should not create those back... 

I notice to quirks that probably are related to base sw:
1- tab content is not refreshed after browser execution. Refresh needs to be pressed
2. there is no way to limit number of tabs as there was in previous non core versions.
3. when there are too many open tabs, last ones are not shown...

TIA
CT

**Comment by crazy-max** [comment]
Hi @caspertone2003,

> A) when launched, it selects a default directory for installation; would like that proposed installation in the directory where the .exe is located and that /brave-portable is not appended authomatically.

I have no way to detect a previous installation through InnoSetup as it is a simple self-extracting setup. Except if I add a registry key on the system but it's not the purpose of portable app :)
But it could be part of portapps/portapps#13 through a thrid party app.

> B) Would like to launch a silent update, to update previous version located in the directory where install exe is located. .exe could detect that there is already a previous version installed in that directory and just question if update or not; after yes, no more questions...

Same as A)

> C) I ususally delete locales that I do not use. Update should not create those back...

It's the default behavior of Chromium based browsers and don't want to affect this as it's user specific.

> I notice to quirks that probably are related to base sw:
> 1- tab content is not refreshed after browser execution. Refresh needs to be pressed
> 2. there is no way to limit number of tabs as there was in previous non core versions.
> 3. when there are too many open tabs, last ones are not shown...

Please create an issue on the official Brave repository, I'm not part or affiliate to Brave core team.

**Comment by caspertone2003** [comment]
Thanks for the answer!
