### ISSUE TITLE
Issue with 0.62.37-12

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#14]
@crazy-max 

When updating from 27-11 (do not know other situations)

First run after update ends bad (flash and exit). A second run is needed to get browser running and then tabs that were open before update are lost; besides, history cannot be opened to recover not opened tabs.

Thanks!
CT

**Comment by crazy-max** [comment]
Hi @caspertone2003, can you post a proper [bug report](https://github.com/portapps/brave-portable/issues/new?template=bug_report.md) please ?

**Comment by caspertone2003** [comment]
### Behaviour

It happens to me when updating to 37-12 from 27-11, having several tabs open.

First run after update ends bad (flash and exit). A second run is needed to get browser running and then tabs that were open before update are lost; besides, history cannot be opened (neither mouse or control+H produce any action) to recover not opened tabs.

#### Steps to reproduce this issue

1. Install 27-11; configure to retain open tabs accross run session (so keep tabs when clossing, open tabs when reopening)
2. Open several tabs
3. Close 27-11 without closing tabs
4. Update to 37-12
5. Run

#### Expected behaviour
> Tell me what should happen
Browser opens showing previously open tabs.

#### Actual behaviour

> Tell me what happens instead
Browser loses open tabs.

### Configuration
???
**App release / arch (ex. 1.0.0-2 win64)** :
0.62.37-12 vs 0.62.27-11

**Operating system (ex. Windows 10 Pro 64 bits)** :
W10 64 bits

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `[appname]-portable.log` to this issue.

Next edit

**Comment by caspertone2003** [comment]
It happened on friday several times but today I am unable to reproduce. Something weird in the PC?
Apologies.
Please close.

**Comment by caspertone2003** [comment]
@crazy-max 

It happened again but not on installation but on use. Lost all tabs.
Log since update to 37-11 attached (I am unsure if just after update or sometime later...)
[brave-portable-sent.log](https://github.com/portapps/brave-portable/files/3002765/brave-portable-sent.log)

**Comment by crazy-max** [comment]
@caspertone2003 

As I can see in your logs, it's an issue with Brave itself : `[8852:1728:0325/111355.697:ERROR:CONSOLE(1)] "Uncaught ReferenceError: brave_new_tab is not defined", source: chrome://newtab/ (1)`

I think it has nothing to do with the portability of the application. Have you checked on the official repo if this problem exists? If not you should open an issue on the official repository about that.
If it'a an upstream issue, I will stay on stable releases of Brave to avoid this kind of problem.

**Comment by caspertone2003** [comment]
Thanks!

**Comment by caspertone2003** [comment]
https://github.com/brave/brave-browser/issues/2848

**Comment by caspertone2003** [comment]
62.47 seems to solve the issue as had no issues with 47-13. Skipped 37-12. Would suggest not using 37-12
CT

**Comment by crazy-max** [comment]
Ok thanks @caspertone2003, I will mark 37-12 as broken.
