### ISSUE TITLE
Multiple profiles

### ISSUE THREAD

**Issue by MagicalDrizzle** [portapps/brave-portable#143]
Is there a way to have multiple profiles in one installation like Phyrox?

**Comment by Chaython** [comment]
It's chromium so yes it supports multiple profiles, click the sandwich in the top right
unlike mozilla based browsers where there's container profiles where they link together, chromium sets the app completely separate instance

**Comment by MagicalDrizzle** [comment]
ah right, I completely forgot chromium worked that way lol
my apologies
