### ISSUE TITLE
New critical Chrome security update 4/26/2024

### ISSUE THREAD

**Issue by sclient** [portapps/brave-portable#158]
Just wanted to point this out here in hopes a new portable version will be out soon as I rely on it as my primary browser, and these things are always pretty concerning. Apologies if this isnt the correct place for it!

https://www.reddit.com/r/technology/comments/1ceeif0/update_now_warning_issued_for_1_billion_google/

**Comment by crazy-max** [comment]
https://github.com/portapps/brave-portable/releases/tag/1.65.126-91
