### ISSUE TITLE
Brave Portable?

### ISSUE THREAD

**Issue by Jasantes** [portapps/brave-portable#160]
**Portable...? What's so portable about this? 
The profile is installed in C:\Users!!!
So in a migration you will lose all your user data!!!**

**Comment by Jasantes** [comment]
Ok, if no one feels encouraged to give an answer, I'll do it myself:
THIS IS A HOAX... THIS IS NOT REALLY PORTABLE!!!

**Comment by crazy-max** [comment]
See https://github.com/portapps/brave-portable/issues/33
