### ISSUE TITLE
Feedback on releases

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#17]
I will be providing feedback of my experiences with the releases, feedback on the portable and its installation, not feedback related to the brave-core itself.

The backlog... I have tried most of the portable releases @Wx64 based on brave-core post portabilization patch. Most ok.

**Comment by caspertone2003** [comment]
0.62.51-14 goes well.

**Comment by caspertone2003** [comment]
Thanks for 0.63.48-15
Smooth update to 0.63.48-15 @W10-x64 / 20190425
No working issues detected.

**Comment by crazy-max** [comment]
@caspertone2003 Thanks

**Comment by caspertone2003** [comment]
Thanks for 0.63.55-16
Smooth update to 0.63.55-16 @W10-x64 / 20190508
No working issues detected.
Confirmed app-path as per https://portapps.io/doc/configuration/ works!
CT

**Comment by caspertone2003** [comment]
@crazy-max 

Thanks for 0.64.75-18
Smooth update from 0.63.55-16 to 0.64-75-18 @W10-x64 / 20190517
No (portable) working issues detected.
CT

**Comment by caspertone2003** [comment]
@crazy-max

Thanks for 0.64.76-19
Smooth update from 0.64-75-18 to 0.64.76-19 @W10-x64 / 20190520
No (portable) working issues detected.
CT

**Comment by caspertone2003** [comment]
@crazy-max

Thanks for 0.64.77-20
Smooth update from 0.64.76-19 to 0.64.77-20 @W10-x64 / 20190525
No working issues of brave-portable detected.
CT

**Comment by caspertone2003** [comment]
@crazy-max

Thanks for 0.65.118-21
Smooth update from 0.64.77-20 (64bits) to 0.65.118-21 (64bits) @W10-x64 / 20190608
No working issues of brave-portable detected.
Let´s try first 65 cut!
Looks more relevant new items are update to Chromium 75 and new layout of settings  - https://github.com/brave/brave-browser/blob/master/CHANGELOG.md 

CT

**Comment by crazy-max** [comment]
Thanks for the update @caspertone2003

**Comment by caspertone2003** [comment]
@crazy-max

Thanks for 0.65.120-22
Smooth update from 0.65.118-21 (64bits) to 0.65.120-22 @W10-x64 / 20190608
No working issues of brave-portable detected.

CT

**Comment by caspertone2003** [comment]
@crazy-max

Thanks for 0.65.121-23
Smooth update from 0.65.120-22 (64bits) to 0.65.121-23 @W10-x64 / 20190608
No working issues of brave-portable detected.

CT

Sad news you had to remove slack portable.
Where could I learn to pack slack as portable myself with portapps technology? I will be unable to use slack as I planned without a portable version... and would avoid cameyo if possible...

Far from my intentions having to replicate your previous work but seems there is no alternative...

Thanks

**Comment by crazy-max** [comment]
> Where could I learn to pack slack as portable myself with portapps technology?

I think I will restore the Slack repository without the releases, only source code. I have to finish the [Contribute page](https://portapps.io/doc/contribute/) first. Keep you in touch.

PS: I lock this thread. If you have an issue with Brave you can open an issue.

**Comment by crazy-max** [comment]
[Slack repo](https://github.com/portapps/slack-portable) is restored and [Contribute page](https://portapps.io/doc/contribute/) updated.
