### ISSUE TITLE
Portable Version 1.71.123.93 - Print error

### ISSUE THREAD

**Issue by Urvish-Patel-007** [portapps/brave-portable#171]
#### Steps to reproduce this issue

1. Open any website or PDF you want to print.
2. Ctrl+P or right click and select Print or any other print command.
3. It says 'Print preview failed.' and I can not even click on 'Print' button which is there beside 'Cancel' button.

#### Expected behaviour - It says 'Print preview failed.' and I can not even click on 'Print' button which is there beside 'Cancel' button.

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead - In place of 'Print preview failed.', there should be a preview of what is about to get printed. Also the 'Print' & 'Cancel' buttons should not be in a disabled position. They should be clickable with the mouse.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
1.71.123.93 Win64 7zArchive

**Operating system (ex. Windows 10 Pro 64 bits)** :
Edition	Windows 11 Pro
Version	23H2
Installed on	‎03-‎Mar-‎24
OS build	22631.4460
Experience	Windows Feature Experience Pack 1000.22700.1047.0

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR
![image](https://github.com/user-attachments/assets/374edb9d-7aba-49e8-8a0f-a1ecf8232c19)

### Screenshots
> 
![image](https://github.com/user-attachments/assets/83213efa-13ce-45ba-8706-d43820ca0a38)

### Logs

[brave-portable.log](https://github.com/user-attachments/files/17913094/brave-portable.log)

**Comment by RIVAX64** [comment]
Hello, I have the exact same problem.

I also use Windows 11 23H2 (22631.4541)

I've used the last two versions 1.71.123-93 (brave-portable-win64-1.71.123-93-setup) and 1.68.134-92 (brave-portable-win64-1.68.134-92-setup.exe) following the instructions in the Portapps installer.
In both versions it is impossible for me to print a selection of text or an entire page in PDF.

However, version 1.65.126-91 (brave-portable-win64-1.65.126-91-setup) does not present this issue, and it is possible to print properly. Although it fails in other aspects because it is an outdated version.

I have tried to apply some suggested setup tips on some web pages without any results. And in fact, with the same settings, the old version 1.65.126-91 prints correctly.

**Comment by PenguinPaws** [comment]
It was an issue in the previous version as well (1.68.134-92), but oddly enough I can't find the Issue # for it on GitHub.

Here's the workaround for anyone that encounters the same problem.

1. Run brave-portable at least the first time, then close it.
2. Rename the file `brave-portable**.sample**.yml` to `brave-portable.yml`
3. Open brave-portable.yml in Notepad, Notepad++, or an editor of your choice.
4. Find the line with this content:
        `args: []`
    Replace with:
        `args: ["--disable-features=PrintCompositorLPAC"]`
5. Save file, and launch Brave portable as normal.

**Comment by Urvish-Patel-007** [comment]
> Hello, I have the exact same problem.
> 
> I also use Windows 11 23H2 (22631.4541)
> 
> I've used the last two versions 1.71.123-93 (brave-portable-win64-1.71.123-93-setup) and 1.68.134-92 (brave-portable-win64-1.68.134-92-setup.exe) following the instructions in the Portapps installer. In both versions it is impossible for me to print a selection of text or an entire page in PDF.
> 
> However, version 1.65.126-91 (brave-portable-win64-1.65.126-91-setup) does not present this issue, and it is possible to print properly. Although it fails in other aspects because it is an outdated version.
> 
> I have tried to apply some suggested setup tips on some web pages without any results. And in fact, with the same settings, the old version 1.65.126-91 prints correctly.

**Comment by Urvish-Patel-007** [comment]
@RIVAX64 Thanks for confirmation of the issue.

@PenguinPaws Your solution worked out properly. Thank you so much. Hope this won't cause any other problem. :)

**Comment by PenguinPaws** [comment]
> @PenguinPaws Your solution worked out properly. Thank you so much. Hope this won't cause any other problem. :)

Happy to have been able to help :)
