### ISSUE TITLE
other releases?

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#18]
@crazy-max 
Looks that brave-core has stopped evolving x.62, with a mad-hurry releases of nighlys x.66 and devs x.65 and also betas x.64 in the last two weeks.

Would you know if they skipped x.63?
Could you make, if not to effort for you, a special release of portable using beta-x.64 or dev-x.65, just to play a bit?

TIA
CT

**Comment by crazy-max** [comment]
@caspertone2003 I'll stay on the [stable channel](https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml) for this repository. But feel free to fork it and create your own releases like I have done for Discord PTB.

**Comment by caspertone2003** [comment]
ok, understood. Unfortunatelty I am not knowledgeable to compile them.
Thanks anyhow
