### ISSUE TITLE
Windows defender complains from trojan horse

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#19]
@crazy-max 

As from today Windows Defender started to quarantine brave-portable.exe (w10@x64). Sad news...

<img width="395" alt="bravetrojan" src="https://user-images.githubusercontent.com/4682903/57585608-ae7b5b80-74ea-11e9-8233-5ff3056138d5.PNG">

my brave-portable.exe (x64) SHA-256 is
8ED6CA07C7B5664865B608D583F5B7443EEC6ECC92AEBB51BC8C4019DA2C83AC

as per http://onlinemd5.com/

as per virustotal is mostly clean (same as downloaded x64 exe, one is signaling malware); can you recheck that your brave-portable.exe has same hash? 

I trust is just a false positive, but it is sad news if Windows Defender has identified that file as a trojan. Can you review the code to see if you can identify the offending section and avoid that nuisance?

TIA

**Comment by crazy-max** [comment]
Hi @caspertone2003,

I have submitted `brave-portable-win64.exe` to Microsoft :

![image](https://user-images.githubusercontent.com/1951866/57585903-77a74480-74ee-11e9-836e-85c873445e56.png)

Will wait for a final determination.

Please see also:
* portapps/portapps#29
* https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper

**Comment by caspertone2003** [comment]
@crazy-max 
Thanks for the quick reaction. Malware false positives is a pest to developpers....
We users only grasp how hard is to keep sw development running! Not only changes and bugs and user requirements and user questions... then, the fight with the tools providers (travis, go, etc.), then... the challenges of anti-malware...
CT

**Comment by crazy-max** [comment]
Signature definitions have been updated:

![image](https://user-images.githubusercontent.com/1951866/57605915-102ddb00-7568-11e9-8739-ce47a33fb744.png)
