### ISSUE TITLE
app_path relative paths do not work.

### ISSUE THREAD

**Issue by kolobok55** [portapps/brave-portable#21]
trying to set relative path to binaries directory like f.e. "app1" or  f.e. "..\app", but it do not work. It feature need for multple instances of brave  with one binaries source.
Another solution is pass config file into run command f.e.:
brave-portable.exe -myconfig1.yml
brave-portable.exe -myconfig2.yml
last option will be better, i can just change user data directory

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/portapps/brave-portable/issues/new?template=bug_report.md).
