### ISSUE TITLE
Can't run setup portable file

### ISSUE THREAD

**Issue by Salin1810** [portapps/brave-portable#23]
### Behaviour
Setup portable file
#### Steps to reproduce this issue

1. Open setup portable file "brave-portable-win64.exe" (already move setup file into root partition folder, permisson is ok)
2. Window errors appearance

#### Expected behaviour
-----
#### Actual behaviour

Setup can't open

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 
0.66.100-25 portable / win 64
**Operating system (ex. Windows 10 Pro 64 bits)** :
Window 7 Pro 64 bits

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/31431375/61812613-0da40780-ae6e-11e9-9aab-b55b54a85c9b.png)

### Screenshots

![image](https://user-images.githubusercontent.com/31431375/61812695-34fad480-ae6e-11e9-886a-f20e8fe1f9c4.png)

### Logs

[brave-portable.log](https://github.com/portapps/brave-portable/files/3427928/brave-portable.log)

**Comment by crazy-max** [comment]
@Salin1810 `brave-portable-win64.exe` is just the wrapper not the full portable release. Download links are provided on the [official Brave portable page](https://portapps.io/app/brave-portable/#download).
