### ISSUE TITLE
Don't create shortcuts in Start Menu/Programs

### ISSUE THREAD

**Issue by tomasz1986** [portapps/brave-portable#24]
### Behaviour

Brave portable keeps creating a shortcut in `Start Menu/Programs` on every launch. The shortcut is then removed upon closing Brave portable. The shortcut is not removed if Brave portable has crashed or the process has been killed forcefully.

#### Steps to reproduce this issue

1. Launch Brave portable.
2. A shortcut to brave-portable.exe is created in Start Menu\Programs.
3. Close Brave portable.
4. The shortcut has been deleted.

or

1. Launch Brave portable.
2. A shortcut to brave-portable.exe is created in Start Menu\Programs.
3. Kill brave-portable.exe with `taskkill /im brave-portable.exe`.
4. Close Brave portable.
5. The shortcut remains.

#### Expected behaviour

With all the respect for your work, I do not believe that a portable application should create such a shortcut at all. Portable applications, by definition, are likely to be launched from a USB device on different machines, and I would expect them not to place any files in the host OS, unless absolutely necessary.

#### Actual behaviour

The Start Menu shortcut is recreated again and again with no option to configure the behaviour, apart from removing the related code

https://github.com/portapps/brave-portable/blob/d6970ff537bf1aca8cc91c0ec498d00195d77997/main.go#L46-L73

and recompiling Brave portable from source.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 0.67.124-28 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 7 Enterprise x64

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/5626656/63220965-f6d2a580-c1cc-11e9-9cea-c2a4b32a219b.png)

### Logs

[brave-portable.log](https://github.com/portapps/brave-portable/files/3512710/brave-portable.log)

**Comment by crazy-max** [comment]
@tomasz1986 As stipulated on [Infos section](https://portapps.io/app/brave-portable/#infos) on brave-portable page, a shortcut is created at launch to allow native notifications and removed when Brave is closed. On Windows 8 / 10, notifications are made through an [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx). A shortcut to the application must be added in the start menu to make desktop notifications working.

> Kill brave-portable.exe with `taskkill /im brave-portable.exe`.

This process to explain reproducibility is rather "overkilled", isn't it? :upside_down_face:

**Comment by tomasz1986** [comment]
I must have missed the bit about allowing notifications when reading the documentation. I am sorry about that :pensive:.

> > Kill brave-portable.exe with `taskkill /im brave-portable.exe`.
> 
> This process to explain reproducibility is rather "overkilled", isn't it? :upside_down_face:

Yes, I agree. The point was that if either the browser, or the operating system itself crashes, the shortcut remains in the Start Menu. If the shortcut is necessary for notifications, then it is probably a necessary evil, so I will close the issue.

**Comment by crazy-max** [comment]
> If the shortcut is necessary for notifications

Yes I don't like it too but I think it leaves a small footprint on the operating system for now.
