### ISSUE TITLE
Move hardcoded flags to brave-portable.yml file, and allow to modify them

### ISSUE THREAD

**Issue by tomasz1986** [portapps/brave-portable#25]
### Behaviour

Brave portable is compiled with specific flags hardcoded.

https://github.com/portapps/brave-portable/blob/d6970ff537bf1aca8cc91c0ec498d00195d77997/main.go#L35-L44

Because of that, the browser is always launched with these flags with no option to configure them by the user.

#### Steps to reproduce this issue

1. Launch Brave portable.
2. Brave portable is launched with 8 flags hardcoded, despite them not being listed in the `brave-portable.yml` file.

#### Expected behaviour

In my opinion, it would be beneficial to move these flags from the actual code to the `brave-portable.yml` file. This way it would be possible to freely modify them for one's own needs. Such an approach is used in [chrlauncher](https://github.com/henrypp/chrlauncher), where all the switches are listed and read from an `.ini` file as follows.

`ChromiumCommandLine=--user-data-dir=..\profile --no-default-browser-check --allow-outdated-plugins --disable-logging --disable-breakpad`

Moving the flags to `brave-portable.yml` would make Brave portable more flexible and customisable, which I believe is a good thing and beneficial for the users.

#### Actual behaviour

The switches

```
--user-data-dir
--disable-brave-update
--no-default-browser-check
--allow-outdated-plugins
--disable-logging
--disable-breakpad
--disable-machine-id
--disable-encryption-win
```

are hardcoded in `brave-portable.exe` with no option to configure (or remove) them manually.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 0.67.124-28 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 7 Enterprise x64

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/5626656/63220973-03ef9480-c1cd-11e9-96fb-a9a443db2067.png)

### Logs

[brave-portable.log](https://github.com/portapps/brave-portable/files/3512710/brave-portable.log)

**Comment by crazy-max** [comment]
@tomasz1986 Those switches are required to handle portability. Which one do you want to remove? Maybe `allow-outdated-plugins`?

**Comment by tomasz1986** [comment]
> @tomasz1986 Those switches are required to handle portability. Which one do you want to remove? Maybe `allow-outdated-plugins`?

Yeah, and it would also be nice to be able to specify the `--user-data-dir` path manually. I just like being able to 100% customise everything :wink:.

**Comment by crazy-max** [comment]
> Yeah, and it would also be nice to be able to specify the --user-data-dir path manually. I just like being able to 100% customise everything

The purpose of portapps applications is to handle portability of applications and not delivering high level of customizations like changing core behaviors (moving data, configuration files, etc..). It could lead to portability loss and I don't want to bring support for this kind of things sorry. But feel free to [fork and build the project yourself](https://portapps.io/doc/contribute/).

PS: I will remove `allow-outdated-plugins` for now.
