### ISSUE TITLE
Add additional switches to reduce cache files creation

### ISSUE THREAD

**Issue by tomasz1986** [portapps/brave-portable#26]
### Behaviour

Chromium by default creates tons and tons of cache files. Not only do they take disk space, but also writing such a large number of files to weak flash memory (e.g. on typical USB flash drives, or SD cards) reduces its lifespan. In addition, it can also be detrimental for performance, as such a flash memory is often too slow to write a large number of small files fast enough, especially since Windows disables write cache for USB devices by default.

#### Steps to reproduce this issue

1. Launch Brave portable.
2. Browse the Internet for some time.
3. Open the `data\Default` folder.
4. Various cache folders (e.g. `Code Cache`, `GPUCache`, `Media Cache`) will be filled with files downloaded by the browser from the visited websites.

#### Expected behaviour

A portable application, by definition, is likely to be launched from a USB device (e.g. a flash drive, an SD card, etc.) whose lifespan is much shorter than standard HDDs or SSDs. For a portable application, I would expect it to take such an environment into account and write as few files as possible to prolong the flash memory lifespan.

I would suggest adding switches such as:

`--aggressive-cache-discard`
`--disk-cache-size=1` (impossible to disable completely)
`--media-cache-size=1` (impossible to disable completely)
`--disable-gpu-program-cache`
`--disable-gpu-shader-disk-cache`
`--v8-cache-options=none` (the worst one, responsible for the `Code Cache` folder which gets filled with tens of thousands of cached JavaScript files taking hundreds of MBs of disk space)

Following https://github.com/portapps/brave-portable/issues/25, I would suggest to have these switches added to `brave-portable.yml` instead of hardcoding them, so that the user would be able to modify them at will.

#### Actual behaviour

Brave portable creates as many cache files as any other Chromium based browser.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 0.67.124-28 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 7 Enterprise x64

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/5626656/63220984-1a95eb80-c1cd-11e9-988a-b9ed1606b42e.png)

### Logs

[brave-portable.log](https://github.com/portapps/brave-portable/files/3512710/brave-portable.log)

**Comment by crazy-max** [comment]
Hi @tomasz1986,

I prefer to keep the standard behaviour of the applications and avoid any alteration as much as possible. But you can already add additional switches if you want in the YAML config. See [Configuration doc](https://portapps.io/doc/configuration/) for more info.

Btw, thanks for your report!

**Comment by tomasz1986** [comment]
Understood. What is your opinion on including these switches in the documentation as an option, though? Right now, there is no detailed information on those available in one place. I myself had to find them either in the Internet, the Chromium source code itself, and also though my own testing.

**Comment by tomasz1986** [comment]
Understood. Just in case, here is some detailed information (where available) on the cache related switches, together with URLs to the actual Chromium source. I must say that I was actually wrong about the `--aggressive-cache-discard` switch, as it appears to be used only in Chromium in Chrome OS, and ignored in the other builds. The `--media-cache-size` switch will also be removed very soon, in Chromium 78.


1. `--aggressive-cache-discard`
```
const char kAggressiveCacheDiscardThreshold[] = "aggressive-cache-discard";
```
https://github.com/chromium/chromium/blob/35f2625ac2da2b5b20e4a2e5a8ae6b61d43c7277/chromeos/constants/chromeos_switches.cc#L35

Note: Actually appears to be intended only for Chromium used in Chrome OS.


2. `--disk-cache-size=1`
```
// Forces the maximum disk space to be used by the disk cache, in bytes.
const char kDiskCacheSize[]                 = "disk-cache-size";
```
https://github.com/chromium/chromium/blob/6f33b3391930f5cc5bb2eb5ca4a6a83a9b56f4f8/chrome/common/chrome_switches.cc#L247-L248


3. `--media-cache-size=1`
```
// Forces the maximum disk space to be used by the media cache, in bytes.
const char kMediaCacheSize[]                = "media-cache-size";
```
Note: Will be removed in Chromium 78.0.3887.5 (https://github.com/chromium/chromium/commit/f99eeb0dc116a6c02383069b7cc4b2276058f6f1).


4. `--disable-gpu-program-cache`
```
// Turn off gpu program caching
const char kDisableGpuProgramCache[]        = "disable-gpu-program-cache";
```
https://github.com/chromium/chromium/blob/d41c9bfb9c45d3ead5026bbc69d4b1ee488a221a/gpu/command_buffer/service/gpu_switches.cc#L37-L38


5. --disable-gpu-shader-disk-cache
```
// Disables the GPU shader on disk cache.
const char kDisableGpuShaderDiskCache[]     = "disable-gpu-shader-disk-cache";
```
https://github.com/chromium/chromium/blob/d41c9bfb9c45d3ead5026bbc69d4b1ee488a221a/gpu/command_buffer/service/gpu_switches.cc#L49-L50


6. `--skia-font-cache-limit-mb=1`
```
// Specifies the max number of bytes that should be used by the skia font cache.
// If the cache needs to allocate more, skia will purge previous entries.
const char kSkiaFontCacheLimitMb[] = "skia-font-cache-limit-mb";
```
https://github.com/chromium/chromium/blob/bccdd030fb01938ffeb2e3ada7c5c2e963a8bb5d/content/public/common/content_switches.cc#L788-L790

Note: Appears to limit the cache in RAM, not on the disk (https://bugs.chromium.org/p/chromium/issues/detail?id=274452).

7. `--skia-resource-cache-limit-mb=1`
```
// Specifies the max number of bytes that should be used by the skia resource
// cache. The previous entries are purged from the cache when the memory useage
// exceeds this limit.
const char kSkiaResourceCacheLimitMb[] = "skia-resource-cache-limit-mb";
```
https://github.com/chromium/chromium/blob/bccdd030fb01938ffeb2e3ada7c5c2e963a8bb5d/content/public/common/content_switches.cc#L792-L795

Note: Appears to limit the cache in RAM, not on the disk (https://bugs.chromium.org/p/chromium/issues/detail?id=274452).

8. `--v8-cache-options=none`
```
// Set options to cache V8 data. (off, preparse data, or code)
const char kV8CacheOptions[] = "v8-cache-options";
```
https://github.com/chromium/chromium/blob/bccdd030fb01938ffeb2e3ada7c5c2e963a8bb5d/content/public/common/content_switches.cc#L398-L399

Note: The available options are actually "Default", "None", "Code", "CodeWithoutHeatCheck", and "FullCodeWithoutHeatCheck" (https://github.com/chromium/chromium/blob/2ca8c5037021c9d2ecc00b787d58a31ed8fc8bcb/third_party/blink/renderer/bindings/core/v8/v8_cache_options.h#L36-L44)

**Comment by crazy-max** [comment]
Thanks I will keep an eye on it
