### ISSUE TITLE
brave-portable 0.68.132-30  contain trojan virus?

### ISSUE THREAD

**Issue by ray4423** [portapps/brave-portable#29]
many antiviurs programs(on virustotal) detect  a trojan.
is this a false positive??

https://www.virustotal.com/gui/file/28bcdb8645d1a9569f3c0bece90bcef238a9a8a205f76160cb671dd00740169d/detection

**Comment by crazy-max** [comment]
As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive.

I have sent the wrapper to Microsoft, Bitdefender and others antivir orgs and the result is, as expected, a false positive.

Looking at the [VirusTotal analysis](https://www.virustotal.com/gui/file/28bcdb8645d1a9569f3c0bece90bcef238a9a8a205f76160cb671dd00740169d/detection), detection has dropped from 22/70 to 15/70 and is expected to be further reduced in the coming days.

If you encounter this problem again you can submit the wrapper yourself to the antivirus companies and report it as false positive. But feel free to open an issue to keep me informed about this.
