### ISSUE TITLE
NativeMessagingHost seems broken after v0.67.124-28

### ISSUE THREAD

**Issue by d-faure** [portapps/brave-portable#30]
### Behaviour

Portable Brave is unable to bind itself to KeePassXC using the ad-hoc extension

#### Steps to reproduce this issue

1. Have both KeePassXC running and configured to enable browser integration and related browser extension installed
2. Connect the KeePassXC extension to the KeePass Database
3. Have some credentials stored in password manager for some page.
4. Shutdown the browser and restart it

#### Expected behaviour

The password manager is still found as running by the extension which can discuss with it.

#### Actual behaviour

The extension is unable to bind itself with the password manager and shows it via its toolbar icon and error message in the related dropdown.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : v0.67.124-28 (OK) / v0.68.131-29 (KO) / v0.68.132-30 (KO)

**Operating system (ex. Windows 10 Pro 64 bits)** : Microsoft Windows [version 10.0.16299.15]

**Winver screenshot** : is it really needed?

### Screenshots

n/a

### Logs

This is more a browser issue than a launcher one, but as you already made what was needed in the browser itself to have it portable.

This seems related to https://github.com/brave/brave-browser/issues/5074

**Comment by crazy-max** [comment]
@d-faure Thanks for your report. This will be useful for other users but I have to close this issue as this is linked to brave itself and not portability handled by Portapps.
