### ISSUE TITLE
Upgrade to the next generation of Brave browser (brave-core)

### ISSUE THREAD

**Issue by crazy-max** [portapps/brave-portable#4]
Some caveats to note before an upgrade to the [next generation of Brave browser](https://github.com/brave/brave-browser).

## Passwords are not saved

Brave (as Chromium) stores passwords in such a way that they are encrypted in a way tied to current PC. While the passwords are not kept or left behind on the PC itself, they won't be retrievable when you move to a new PC.

## Certificates not portable

Brave (as Chromium) has no certificate manager. It uses Windows certificates manager. So, any certificates you install through the Brave interface are stored on the current local machine and will not be portable.

## Some settings and extensions are locked per machine

Brave (as Chromium) locks specific settings to a given PC. This behavior is by design by the Chromium team. If you would like this changed, please open an issue on the [brave-core](https://github.com/brave/brave-core) repository. [A suggested workaround](https://rendezvouswithpavan.wordpress.com/2012/12/19/are-your-google-chrome-extensions-disappearing-out-of-nowhere-heres-a-temporary-fix/) is to sign in to _Brave Safe Storage_ to restore all settings and extensions but this is not available on the current release of Brave.

And as stipulated in [this thread](https://support.brave.com/hc/en-us/articles/360017903152-How-do-I-reset-Brave-settings-to-default-) :

> ### Brave reset my browser settings
> Sometimes, programs that you install can change your Brave settings without you knowing. For your safety, the browser checks if your settings have been changed every time you launch Brave. If Brave notices that something’s not right in your settings, it will automatically go back to the original settings.
>
> ### Settings that might automatically get reset
> * Default search engine
> * Homepage
> * Startup pages
> * Pinned tabs
> * Extensions

These issues are specific to Brave due to Chromium's design and not something we can work around without fixes to [brave-core](https://github.com/brave/brave-core).

## Import profile data from Muon

The current stable release (0.55) cannot handle migration of profile data from Muon but there is a work in progress. See brave/brave-core#729

## Linked threads

* brave/brave-browser#694
* Eloston/ungoogled-chromium#444

**Comment by crazy-max** [comment]
See brave/brave-browser#694

**Comment by caspertone2003** [comment]
Chrome portable has fighted this issue for a long time. Their conclusion is that there is no solution, only workarounds.
See
https://portableapps.com/apps/internet/google_chrome_portable

**Comment by crazy-max** [comment]
@caspertone2003 I maybe have a solution with a patch of Chromium. I will open a PR on brave-core repository when my tests are ok.

**Comment by bnscv** [comment]
Don't know if it is of any help, but Iridium Browser has an official portable version and it's also Chromium based. They  recommend creating a shortcut using `--user-data-dir=/IridiumUserData`.
Links: 
https://iridiumbrowser.de/downloads/windows
https://github.com/iridium-browser

**Comment by crazy-max** [comment]
@bnscv `--user-data-dir` is not enough. We have to deal with machine ID and encryption otherwise extensions, passwords and settings are not saved across computers. That's why I have created this PR : brave/brave-core#795

**Comment by caspertone2003** [comment]
It is clear that @crazy-max  is knowledgeable of what s/he does...

**Comment by bnscv** [comment]
> It is clear that @crazy-max is knowledgeable of what s/he does...

Not sure if this was directed to me, but I never said @crazy-max is not knowledgeable of what he/she does, I only wanted to point that Iridium has an official portable build, so **maybe** they have dealt with this in some way, sorry if it sounded like anything else.

**Comment by caspertone2003** [comment]
@bnscv 
It was just a neutral comment, not even pointing to you, reassuring anyone reading the thread, triggered by his/her deep understanding of the issue.
No bad feelings ;-)

**Comment by caspertone2003** [comment]
Any news about your patch to brave-core?
Seems not progressing or even withdrawn
Thanks

**Comment by caspertone2003** [comment]
done
Thanks

**Comment by caspertone2003** [comment]
@crazy-max 
I am not an expert in PR /Github but looks like something could be pending on your side
"This branch has conflicts that must be resolved"
And furthermore, dev version has increased 
Thanks again

**Comment by crazy-max** [comment]
@caspertone2003 Nop it's not. I only wait until my PR is approved before resolving conflicts. No need to work for nothing :upside_down_face:

**Comment by caspertone2003** [comment]
Thanks for enlightning me ;-)

**Comment by crazy-max** [comment]
Give it a try : https://portapps.github.io/news/2019-01-31-brave-portable-0.61.5-45/
