### ISSUE TITLE
Brave hangs on "Save and fill payment methods" page, can crash

### ISSUE THREAD

**Issue by Ergonomicmike** [portapps/brave-portable#42]
First, I am NOT running a vanilla Win10. So the first thing someone should do it test to see if this happens on a vanilla Win10. If not, then it's just me.

Settings > scroll down to "Additional Settings" > Autofill > Payment Methods
When I enter the page, Brave hangs after about 5 seconds. 
I get a Win10 Blue rotation circle for about a minute.
If, after the hang clears, I slide the "Save and fill payment methods" to OFF, everything works as it should. 

But, If, before the 5 second hang, I move the "Save and fill payment methods" to OFF, then Brave locks up. (Win10 white screen, app not responding.)

### Configuration

brave-portable-win64-1.1.23-44, running in a Comdo sandbox. NOT set as default browser.

Win10 64 Home, 1903, Many components removed via NTLite. Lots of Services disabled.

1903. No cummulative updates.

[brave-portable.log](https://github.com/portapps/brave-portable/files/4000818/brave-portable.log)

**Comment by crazy-max** [comment]
@Ergonomicmike 

Are you able to reproduce with the official setup of Brave without portability? I think this issue is related to brave itself and not portability handled by Portapps.

> in a Comdo sandbox

Are you able to reproduce without running on COMODO Sandbox?

**Comment by Ergonomicmike** [comment]
I feel kind of stupid now. I ran Brave Portable outside the COMODO Sandbox and it running fine. So this seems causal with COMODO. (I'll make a report in their forum.)

Interestingly, I couldn't log into github from inside the Sandbox. I got a hang while Brave was trying to secure the site. So it seems like something in Brave is trying to reach out into Windows (10) to make a secure connection.
