### ISSUE TITLE
Default browser: Problem with profiles.

### ISSUE THREAD

**Issue by VirtualW** [portapps/brave-portable#47]
Hi!:
Thank you for your excellent work. I really like this browser and I needed the portable version.

However I have a problem. When I put Brave as a default browser and want to open a link from another program (suppose Thunderbird for emails) Brave opens another "empty" profile without access to my addons, tabs, etc. From "brave://version" I see that the Profile Path of both Brave browsers is different. And Windows is slowly filled with garbage, which I supposedly want to avoid using portable applications.
I want Brave to always open with my personalized profile and that everything is "self-contained" in your folder.

This I could solve in Firefox by accessing "about: profiles" and managing the profile that interested me. But in Brave/Chrome I found no way to modify this.

I was testing from the YAML file (https://portapps.io/doc/configuration/) but maybe because of my ignorance I had no positive results.
I do not think it is that complicated. Any idea how to solve this?

Thanks in advance!.

**Comment by crazy-max** [comment]
Hi @VirtualW,

Default browser capability is not supported for portable apps right now to avoid conflict with the system. Default programs or Default apps on Windows are intended to be used with installed applications on the system.
