### ISSUE TITLE
updating to 0.55 fails

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#5]
### Behaviour
tried to update from .22 to .55 and lost all configuration and information.
Had a backup ;-)

#### Steps to reproduce this issue

1. Install 0.22
2. pin some tabs, make some bookmarks
3. update to 0.55 using exe

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
win64
**Operating system (ex. Windows 10 Pro 64 bits)** :
W10P64 18xxx
**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `brave-portable.log` to this issue.

**Comment by crazy-max** [comment]
@caspertone2003 Duplicated of #4 (read the section _Import profile data from Muon_)
