### ISSUE TITLE
Brave Rewards not working (no ads)

### ISSUE THREAD

**Issue by andZer31** [portapps/brave-portable#53]
One of the main benefits of Brave browser is to earn BAT with Brave Rewards, but it does not work with the portable version.

Wanted ads are shown as notifications, but I still got none in the last few days. Users with the non-portable App had the same issue when Brave did no appear in the Windows Action Center, when it was not listed under notifications

Problem was solved for them when they triggerd a notification manuelly e.g. @ https://www.bennish.net/web-notifications.html, after that Brave appeard in the list of apps with notifications. The portable version does not appear in the list. Another way was to force notifications by going to brave://flags/ and set #enable-native-notifications to enabled. But Brave is still not shown in the notifications list of windows and no ads are shown.

In your Modfications list you write: A shortcut is created at launch to allow native notifications and removed when Brave™ is closed
Can not confirm that, Bug? That is way no ads are shown?

Tested 1.5.115-51 and 1.4.96-50 Win64

Regards

**Comment by crazy-max** [comment]
@andZer31 Thanks for your report. It looks like the AMUID of Brave has changed. Can you try the latest release (1.5.123-53)?

**Comment by andZer31** [comment]
> @andZer31 Thanks for your report. It looks like the AMUID of Brave has changed. Can you try the latest release (1.5.123-53)?

Hi @crazy-max 
Removed the previous version 1.5.123-51 (also files in C:\User\username\appdata\local\ and in Registry HKCU\Software) and installed the 1.5.123-53, but still the same issue. Brave is not appearing in the notifications & actions list, nor while closed neither while opened. Also triggering a notification with https://www.bennish.net/web-notifications.html did not change it. Brave Redwards are activated, no ads showing up (just using it for one hour now, maybe ads will show up later, but I do not think so). In the meanwhile on a linux machine with the non-portable version three ads appeared. 
Regards

**Comment by andZer31** [comment]
Update: Using version 1.5.123-53 since three days and no ads appeared, on linux machine with non-portable version and on mobile android version in the meantime about 10-15 appeared each.

**Comment by andZer31** [comment]
@crazy-max 
Installed Version 1.7.98-55 on a Win10 1909 x64 system, where 1.5.123-53 had the no ads issue, and the problem is solved now.
With version 1.7.98-55 brave portable is still not listed under notifications, but Brave rewards is working and wanted ads are shown as notifications now. Well done, bug is gone :)
