### ISSUE TITLE
Question: is brave also forcing logging to google?

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#6]
### Behaviour

As explained here.
https://techcrunch.com/2018/09/26/google-to-give-chrome-users-an-opt-out-to-forced-login-after-privacy-backlash/?guccounter=1

#### Steps to reproduce this issue

1.
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :

**Operating system (ex. Windows 10 Pro 64 bits)** :

**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `brave-portable.log` to this issue.

**Comment by crazy-max** [comment]
@caspertone2003 For this question open an issue on the [official repository](https://github.com/brave/brave-browser) please. Thanks
