### ISSUE TITLE
win32 1.1.10.93-59 detected trojan by Windows Defender

### ISSUE THREAD

**Issue by mastino21** [portapps/brave-portable#61]
Got brave portable quarantined by Windows Defender.
Virustotal scan of the downloaded installed returned 3 detections:

https://www.virustotal.com/gui/file/8c6a3b5a5a120b2da554e6c72f53fcfe011e521ba3b89cdaa410033f853f0542/detection

I hope they are false positive.

**Comment by crazy-max** [comment]
https://github.com/portapps/brave-portable/issues/29#issuecomment-531419448
