### ISSUE TITLE
The virustotal safety check links on the releases page turn up lots of malware/virus reports

### ISSUE THREAD

**Issue by st333v** [portapps/brave-portable#63]
Its great that you have virustotal links for the .exe files for the win32 and win64 versions of Brave Portable on the Releases page, but not so great that both virustotal links turn up quite a few warnings that the of Brave portable exe files are infected, why is this?
![image](https://user-images.githubusercontent.com/165368/87513588-dd520c00-c670-11ea-9de4-c6113262b482.png)
![image](https://user-images.githubusercontent.com/165368/87513686-05416f80-c671-11ea-8510-5681370431ce.png)

**Comment by crazy-max** [comment]
@st333v See https://github.com/portapps/brave-portable/issues/29#issuecomment-531419448
