### ISSUE TITLE
Portable Brave Update Issue

### ISSUE THREAD

**Issue by WrongGuy** [portapps/brave-portable#72]
Everytime if there is new update, we have to download it separately and overwrite on the existing locations. Can you do something about it like portableapps are doing, they have a software which updates the instances on their particular locations. This will not only be helpful for brave but also for all other portapps you provide as well.
It will take the portapps to next level.

**Comment by crazy-max** [comment]
@WrongGuy See portapps/portapps#13 and portapps/portapps#37
