### ISSUE TITLE
1.17.73-67 not work on Windows 10

### ISSUE THREAD

**Issue by rampageX** [portapps/brave-portable#75]
#### Steps to reproduce this issue

1. download brave-portable-win64-1.17.73-67.7z
2. unpack to replace old version
3. start

#### Expected behaviour

> brave start

#### Actual behaviour

> nothing happen

### Configuration

**brave-portable-win64-1.17.73-67.7z or win32 version

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Ent x64

**Winver screenshot** : Microsoft Windows [Version 10.0.19042.662]

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@rampageX Should be fixed with [1.17.75-68](https://github.com/portapps/brave-portable/releases/tag/1.17.75-68)
