### ISSUE TITLE
Brave portable link gets deleted from Windows start menu

### ISSUE THREAD

**Issue by alexeiz** [portapps/brave-portable#77]
### Behaviour

Brave start menu link is created on start but then deleted when the app exits.

#### Steps to reproduce this issue

1. Start Brave portable with this app.
2. Open Windows start menu: Brave portable link appears in the menu.
3. Exit Brave.
4. Open Windows start menu: Brave portable link disappeared.

#### Expected behaviour

> Tell me what should happen

Brave portable start menu link persists so it can be used to launch Brave again.

#### Actual behaviour

> Tell me what happens instead

Brave link deleted from Windows start menu.

**Comment by crazy-max** [comment]
@alexeiz This is the expected behavior. See https://github.com/portapps/phyrox-portable/issues/16#issuecomment-578127524.
