### ISSUE TITLE
0.25.2-40 not fully portable

### ISSUE THREAD

**Issue by caspertone2003** [portapps/brave-portable#8]
I am a fan of the .25 version, I do not like .55, not only for the look but mostly I need session tabs.
So, I would appreciate solving issues on .25 also.
TIA

### Behaviour
0.25.2-40 Creates a brave directory under user/AppData/Roaming

#### Steps to reproduce this issue

1. install
2. make active some extensions
3. look under Roaming

#### Expected behaviour
Full portable means all stuff is computer indepedent, so all should be packed together

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** :
0.25.2-40

**Operating system (ex. Windows 10 Pro 64 bits)** :
win 10 64 pro
**Winver screenshot** :

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `brave-portable.log` to this issue.

**Comment by crazy-max** [comment]
Hi @caspertone2003, I will take a look on this issue. Concerning 0.55, I think it can be solved with my PR brave/brave-core#795

**Comment by caspertone2003** [comment]
@crazy-max 
Checked, fully portable now!
Thanks

**Comment by caspertone2003** [comment]
@crazy-max 
> Hi @caspertone2003, I will take a look on this issue. Concerning 0.55, I think it can be solved with my PR [brave/brave-core#795](https://github.com/brave/brave-core/pull/795)

Bit confused. I know about your PR; but it is covering session tabs?
As per last comment in https://community.brave.com/t/containers-tabs-session-tabs/32212/5  on 4th Oct
"And session tabs/windows not yet implemented for Brave Beta or Brave Dev." (brave-core)

Another comment stated "This type of feature is not likely to be implemented in the current live release of Brave. It is, however, to be implemented with Brave 1.0."

And in 
https://github.com/brave/brave-browser/releases
There is no hint of session tabs already back... :-(

**Comment by crazy-max** [comment]
> Checked, fully portable now!
> Thanks

@caspertone2003 Glad to here :)

> Bit confused. I know about your PR; but it is covering session tabs?

No, my PR just cover protability

**Comment by caspertone2003** [comment]
@crazy-max 
Understood!
You where talking portability in brave-core.
Thanks again

**Comment by caspertone2003** [comment]
@crazy-max 
By the way, I would be more than happy to try your fully portable brave-core "fork" if you provide me a link... Usually only have time on WE so I am not fast...
Thanks

**Comment by crazy-max** [comment]
@caspertone2003 I'm struggling to create a release for the moment, I just have a debug release. The build process broke while creating a final release. I keep you in touch ;)
