### ISSUE TITLE
Command Failed

### ISSUE THREAD

**Issue by Chaython** [portapps/brave-portable#81]
#### Steps to reproduce this issue

1.Download 7z brave-portable-win64-1.20.110-71
2. click brave-portable
3. get error

#### Expected behaviour

> opens app

#### Actual behaviour

> "Command failed"

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : brave-portable-win64-1.20.110-71

**Operating system (ex. Windows 10 Pro 64 bits)** : win 10 x64 2004

**Winver screenshot** : 
![image](https://user-images.githubusercontent.com/6486343/111122441-adc30e80-8533-11eb-8226-b84f1e752819.png)

> Open a command prompt and type winver then take / save the screenshot of the window and drag the image file in this issue. For example: http://bit.ly/2vA5sxR

### Screenshots
![image](https://user-images.githubusercontent.com/6486343/111122468-b6b3e000-8533-11eb-9e26-ae8d88dd95ce.png)

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by crazy-max** [comment]
@Chaython Cannot reproduce your issue. Please attach your logs.

**Comment by Chaython** [comment]
With brave-portable-win64-1.23.71-72 I am no longer experiencing the issue. Thanks.
