### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by webgoto** [portapps/brave-portable#82]
The latest brave version is 1.23.71, so please update.
Thank you.

**Comment by RC-14** [comment]
You can update your Brave version yourself.

Note: Newer/Older versions of brave may not be compatible with the current brave-portable version and I didn't test if brave-portable is still portable after doing this. (I don't know if this breaks anything but as far as I can tell it doesn't.)

Steps:
1. Download the installer you need. ([32bit](https://brave-browser-downloads.s3.brave.com/latest/brave_installer-ia32.exe) or [64bit](https://brave-browser-downloads.s3.brave.com/latest/brave_installer-x64.exe))
2. Extract "chrome.7z" from the installer. ([Universal Extractor 2](https://github.com/Bioruebe/UniExtract2) worked for me)
3. Extract the "Chrome-bin" folder from "chrome.7z".
4. Delete/Move all files in the "app" folder inside of the folder you installed brave-portable to (something like "G:\my\path\brave-portable").
5. Move all files inside of "Chrome-bin" to the "app" folder.

**Comment by crazy-max** [comment]
Available: https://portapps.io/app/brave-portable/#download
