### ISSUE TITLE
app cleanup: true, resets local installation of Brave

### ISSUE THREAD

**Issue by AdKiller** [portapps/brave-portable#83]
#### Steps to reproduce this issue

1. install and customize a local installation of Brave
2. set app cleanup: true in brave-portable.yml
3. open and close portable brave
4. local installation of Brave is reset to default.  that is, C:\...\User\AppData\Local\BraveSoftware\ is deleted! 

#### Expected behaviour
Local installation of Brave should not be affected by portable Brave.

### Configuration

1.23.71-72 (2021/04/18)
Brave 1.23.71
Portapps 3.3.0

Brave local installation: Version 1.23.75 Chromium: 90.0.4430.93 (Official Build) (64-bit) 

**Operating system** : Windows 10 Pro 64 bits v1909 OS build 18363.1440

**Comment by crazy-max** [comment]
@AdKiller Set `cleanup: false`.
