### ISSUE TITLE
DNS Leak

### ISSUE THREAD

**Issue by jamalso** [portapps/brave-portable#84]
I'm using a VPN, which normally have no DNS leak : all ports are closed.... BUT when using Brave I start having DNS leaks while when using Firefox with the same IP I don't have this issue!
![image](https://user-images.githubusercontent.com/19812758/117319603-5f6f2380-ae83-11eb-9616-06d18346a732.png)
![image](https://user-images.githubusercontent.com/19812758/117319634-67c75e80-ae83-11eb-8013-0a8739816f16.png)

**Comment by crazy-max** [comment]
Portapps don't bring support directly to provided apps. If you've got an issue with Brave, open an issue on the [official repository](https://github.com/brave/brave-browser). Thanks.
