### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Aqua1ung** [portapps/brave-portable#86]
I have been attempting to follow the instructions posted [here](https://portapps.io/doc/configuration/) in order to change Brave's `data` folder path, to no avail. Would you guys please have mercy and post an actual `brave-portable.yml` sample file that shows how to change the location to, say, `C:\Users\jake\PortableAppsTemps\Brave\data`?

**Comment by crazy-max** [comment]
https://github.com/portapps/nextcloud-portable/issues/7#issuecomment-578135069
