### ISSUE TITLE
(Question) Can i trust this project ?

### ISSUE THREAD

**Issue by RandomPenguin1778** [portapps/brave-portable#88]
Hi,
I really love brave and wanted to check out brave portable . but i have a privacy concern . since Crazy-Max or another person (which is not with brave) made this how can i trust they dont take my data ?

**Comment by crazy-max** [comment]
@RandomPenguin1778 

* https://portapps.io/doc/faq/
* https://github.com/brave/brave-browser/issues/694

Brave portable is also approved by their VP Engineering.
