### ISSUE TITLE
Dev build way out of date

### ISSUE THREAD

**Issue by Aidolii** [portapps/brave-portable#9]
0.55.20-41 is the dev version available via this project, but the current dev version is up to 0.58.10

There's also a beta build at 0.57.8

Source: https://github.com/brave/brave-browser/releases

**Comment by crazy-max** [comment]
@Aidolii I wait for my PR to be validated and merged by brave team before continuing to produce portable releases for 0.5x versions
If you want the process to go faster, leave a comment and a +1 on my PR : https://github.com/brave/brave-core/pull/795

**Comment by Aidolii** [comment]
Done

**Comment by caspertone2003** [comment]
@crazy-max 

Hello,
on a side line with this, have you a fixed approach on how to follow the (too?) frequent brave-core dev/stable releases?

I mean, you generated two 0.61 in five days following dev updates; I tried to find out the changes in brave-core github from one to the other and it seems that it is not quite easy. Perhaps the second was a mainly a test to try TravisCI... Perhaps this helps you to automate releases?

So, do you plan to produce a release for each Dev release?
Will you be producing releases for brave-core stable releases when your patch reaches stable releases?

TIA again,
CT

**Comment by crazy-max** [comment]
@caspertone2003 I follow updates of 0.61 branch by comparing commits on brave-core and create portable release when I've got time. I don't plan to automate releases to avoid regressions.

**Comment by caspertone2003** [comment]
Thanks for the info.

**Comment by caspertone2003** [comment]
@crazy-max 
just for clarity, my question was only curiosity, not a demand or an Spanish inquisition.

**Comment by Aidolii** [comment]
You could set up this git with AppVeyor at least, so people could download binaries that are generated outside of releases.
