### ISSUE TITLE
[UPDATE VERSION REQUEST] Brave 1.31.91

### ISSUE THREAD

**Issue by STSMHQ** [portapps/brave-portable#92]
@crazy-max I don't know if the correct procedure is to open an issue, but I would like to request an update of this wrapper to the latest version available, please.

![image](https://user-images.githubusercontent.com/94048176/141654974-5c7e2ab6-fa9a-42e2-b34c-b7425781cf9b.png)

**Comment by crazy-max** [comment]
@STSMHQ As explained [on this page](https://portapps.io/doc/reporting-issue/): "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.".

**Comment by STSMHQ** [comment]
> 

Okay. Sorry for that and thanks for your work, one more time :3

**Comment by Chaython** [comment]
> @crazy-max I don't know if the correct procedure is to open an issue, but I would like to request an update of this wrapper to the latest version available, please.
> 
> ![image](https://user-images.githubusercontent.com/94048176/141654974-5c7e2ab6-fa9a-42e2-b34c-b7425781cf9b.png)

Could maybe write a manual updating script with a regression warning...
Any Brave -win32-x64.zip release from https://github.com/brave/brave-browser/releases can be extracted from the zip to the portable app app folder you can then delete the previous release's folder... 

Use something like: https://gist.github.com/MarkTiedemann/c0adc1701f3f5c215fc2c2d5b1d5efd3

**Comment by STSMHQ** [comment]
@Chaython Sorry for the delay replying this. Thanks for the suggestion. It works pretty well.
