### ISSUE TITLE
Flickering when watching any video and distorted text

### ISSUE THREAD

**Issue by elyckir** [portapps/brave-portable#94]
This problem only started after updating to the newest version of brave-portable.
v1.28.106-76
![1 32 106-78](https://user-images.githubusercontent.com/67302729/146189830-fe384342-6a1f-43f6-a290-fcf2a5824eed.gif)
v1.32.106-78
![1 28 106-76](https://user-images.githubusercontent.com/67302729/146189856-e5343911-e556-4a4d-8468-46f772e3796b.gif)

Going to brave://flags/ -> Choose ANGLE graphics backend -> OpenGL 
helps mitigate the flickering. But can later cause crashes. And the distorted text and video is still a problem.

**Comment by elyckir** [comment]
The difference is subtle in the screenshots but substantial in real-time and especially so in videos. 
![brave_2021-12-15_07-42-31](https://user-images.githubusercontent.com/67302729/146191613-74f63f4c-dd12-4607-b19b-d38b9abd8754.png)

In the meantime, I will use the previous version

**Comment by crazy-max** [comment]
Don't think that's related to the portability of Brave itself. Suggest to open an issue on the upstream repo: https://github.com/brave/brave-browser
