### ISSUE TITLE
Trojan - Heuristic

### ISSUE THREAD

**Issue by compusolve-rsa** [portapps/brave-portable#96]
#### Steps to reproduce this issue

1. Download brave-portable from portapps
2. Install on WIN10 with 360 Total Security
3. See popup warning about trojan/heuristic

#### Expected behaviour

Not number 3

#### Actual behaviour

Brave-portable dead in the water, will not launch after trojan removed

### Configuration

WIN10 pro 64
360 Total Security
brave-portable

**Operating system (ex. Windows 10 Pro 64 bits)** :

Win10 pro 64bit, 2004 osbuild 19041.450

### Screenshots

![brave-portapps](https://user-images.githubusercontent.com/57045156/151170891-c57ae1ca-1cfb-492e-a7f4-cfe3a71e2a08.jpg)

**Comment by crazy-max** [comment]
@compusolve-rsa https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper
